# action.yml
name: 'ghsettings'
description: 'Configure Github Settings for Organisations'
runs:
  using: 'docker'
  image: 'docker://mkrakowitzer/actions-ghsettings:latest'

branding:
  icon: 'activity'
  color: 'green'
